# Generated by Django 2.0.9 on 2018-12-24 23:06
import names
import random
from django.db import migrations


def generate_data(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    Department = apps.get_model('employees', 'Department')
    departments = Department.objects.all()

    for _ in range(100):
        Employee.objects.create(
            empName=names.get_full_name(gender=random.choice(['male', 'female'])),
            empActive=random.random() > 0.3,
            empDepId=random.choice(departments)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_data)
    ]
